### PR TITLE
Fixing local compose setup

### PR DESCRIPTION
**Pull request by vishnuchalla**
## Type of change

- [ ] Refactor
- [ ] New feature
- [x] Bug fix
- [ ] Optimization
- [ ] Documentation Update

## Description

Fixing `local-compose.sh` for easy local setup.

## Checklist before requesting a review

- [x] I have performed a self-review of my code.
- [ ] If it is a core feature, I have added thorough tests.

## Testing
Run `local-compose.sh` and get the UI up and running, if specified with right credentials in toml file.

### CODE REVIEW

**Review by jtaleric — COMMENTED** [review]
hm - this is curious -- you needed this to have local-compose work?

**Comment by vishnuchalla** [comment]
> hm - this is curious -- you needed this to have local-compose work?

Yes. CMD looks like taking endpoints hits as arguments and erroring out at runtime.

**Comment by jtaleric** [comment]
> > hm - this is curious -- you needed this to have local-compose work?
> 
> Yes. `CMD` looks like taking endpoints hits as arguments and erroring out at runtime.

odd.. I do not have this issue.. ill ping you directly

**Review by jtaleric — APPROVED** [review]
tested locally and doesn't break my env -- I never had an issue w/ CMD vs Entrypoint. happy if this helps others.

**Pull request merged**
