### PR TITLE
Added the redux store, homepage

### PR DESCRIPTION
**Pull request by athiruma**
## Type of change

- [x] Refactor
- [ ] New feature
- [ ] Bug fix
- [ ] Optimization
- [ ] Documentation Update

## Description
1. Added the React-Redux store to the Site.
    1. Added the redux store for only /jenkins, /jobs and /airflow endpoints. 
2. Added the summary home page using cards.

## Related Tickets & Documents

- Related Issue #
- Closes #

## Checklist before requesting a review

- [ ] I have performed a self-review of my code.
- [ ] If it is a core feature, I have added thorough tests.

## Testing
- Please describe the System Under Test.
- Please provide detailed steps to perform tests related to this code change.
- How were the fix/results from this change verified? Please provide relevant screenshots or results.

### CODE REVIEW

**Comment by athiruma** [comment]
@krishvoor @chentex ptal 👋

**Comment by jtaleric** [comment]
Screenshot from 2023-09-14 14-45-02

So these metrics are a bit of a misnomer as they are only reporting the successes/failures indexed into ES..

We should try to get more of a breakdown based on the JOB names indexed into ES.

**Comment by svetsa-rh** [comment]
In addition to what Joe said, it will be nice to know the details/filters of what the displayed count means (for ex: what filters were used to get this info) and Also ability to drill down based on success/failure runs etc..

**Comment by jtaleric** [comment]
@athiruma this still relevant or can we close?

**Comment by athiruma** [comment]
> @athiruma this still relevant or can we close?

We can close this. ❌

**Comment by athiruma** [comment]
Updated with a new page.

**Pull request closed without merging**
