### PR TITLE
Minor fixes

### PR DESCRIPTION
**Pull request by athiruma**
## Type of change

- [ ] Refactor
- [ ] New feature
- [x] Bug fix
- [ ] Optimization
- [ ] Documentation Update

## Description
Fixed the date picker issue, and "blank" benchmark issue.

## Related Tickets & Documents

- Related Issue #
DatePicker [issue](https://github.com/cloud-bulldozer/ocp-perf-dashboard/issues/32)
Blank Benchmark [issue](https://github.com/cloud-bulldozer/ocp-perf-dashboard/issues/33

- Closes #

## Checklist before requesting a review

- [ ] I have performed a self-review of my code.
- [ ] If it is a core feature, I have added thorough tests.

## Testing
- Please describe the System Under Test.
- Please provide detailed steps to perform tests related to this code change.
- How were the fix/results from this change verified? Please provide relevant screenshots or results.
Screenshot 2023-09-30 at 11 27 00 AM
Screenshot 2023-09-30 at 11 26 53 AM

### CODE REVIEW

**Review by krishvoor — APPROVED** [review]
/lgtm

**Review by vishnuchalla — APPROVED** [review]
lgtm

**Review by chentex — APPROVED** [review]

**Comment by chentex** [comment]
Is this replacing #31 Also??

**Comment by athiruma** [comment]
> Is this replacing #31 Also??

yes.

**Review by dry923 — APPROVED** [review]
LGTM!

**Comment by jtaleric** [comment]
lgtm I will drop mine.

**Comment by athiruma** [comment]
> lgtm I will drop mine.

ack

**Pull request merged**
