### PR TITLE
Trending Data

### PR DESCRIPTION
**Pull request by jtaleric**
## Type of change

- [ ] Refactor
- [x] New feature
- [ ] Bug fix
- [ ] Optimization
- [ ] Documentation Update

## Description
Adding some trending data to help us track resource utilization across runs

## Related Tickets & Documents

- Related Issue #
- Closes #

## Checklist before requesting a review

- [ ] I have performed a self-review of my code.
- [ ] If it is a core feature, I have added thorough tests.

## Testing
- Please describe the System Under Test.
- Please provide detailed steps to perform tests related to this code change.
- How were the fix/results from this change verified? Please provide relevant screenshots or results.

### CODE REVIEW

**Comment by jtaleric** [comment]
> Code changes look good to me at this moment, as this project is still growing. Once we have enough cases added I think we can consider some refactoring.

yes! I totally agree -- the code can be improved -- due to the iterative nature it is ugly but can be totally improved!

**Review by chentex — APPROVED** [review]
LGTM

**Comment by jtaleric** [comment]
Only thing I want to add is a simple new dashboard showing some trending results.

**Review by chentex — APPROVED** [review]
LGTM

**Pull request merged**
