### PR TITLE
New Home page based on the new design mockup

### PR DESCRIPTION
**Pull request by athiruma**
## Type of change

- [x] Refactor
- [x] New feature
- [ ] Bug fix
- [ ] Optimization
- [ ] Documentation Update

## Description

Re-Design the home page.
New Additions:
1. React Redux
2. Home page in a single page.

Backend:
1. Changed the elasticsearch datetime to date type

## Related Tickets & Documents
[https://issues.redhat.com/browse/PERFSCALE-2445](https://issues.redhat.com/browse/PERFSCALE-2445)

- Related Issue #
- Closes #

## Checklist before requesting a review

- [ ] I have performed a self-review of my code.
- [ ] If it is a core feature, I have added thorough tests.

## Testing
- Please describe the System Under Test.
- Please provide detailed steps to perform tests related to this code change.
- How were the fix/results from this change verified? Please provide relevant screenshots or results.
Screenshot 2023-09-24 at 11 25 19 PM

### CODE REVIEW

**Comment by athiruma** [comment]
FIW, I Created a new branch named **test** and opened the PR, once all is good in the **test** will move to the **main** branch.

**Comment by krishvoor** [comment]
Hey @athiruma can you move this PR draft and once your the initial version ready, open it up for review?

**Comment by athiruma** [comment]
> Hey @athiruma can you move this PR draft and once you have the initial version ready, open it up for review?

No more changes. Ready for review.

**Review by chentex — CHANGES_REQUESTED** [review]
Awesome work @athiruma!!! This is looking great! I added a couple of comments, minor, and have another request, I know the mock-up was in blue, but could we change the color palette, to Red Hat red.

The other thing is could we leave the other tabs for the moment since they contain functionality that we don't have yet here? Like sorting, and showing details of the Jobs?

**Review by chentex — APPROVED** [review]
Great work!

**Review by krishvoor — APPROVED** [review]
lgtm :-)

**Comment by jtaleric** [comment]
Nice.

Curious - why do we see 3 different scroll bars for the homepage? Can we reduce this? 
image

also, the narrowing on workload / size / etc -- can we carry this on for each CI System (Prow and Jenkins)?

**Comment by athiruma** [comment]
> Nice.
> 
> Curious - why do we see 3 different scroll bars for the homepage? Can we reduce this? image
> 
> also, the narrowing on workload / size / etc -- can we carry this on for each CI System (Prow and Jenkins)?

Done.

**Comment by jtaleric** [comment]
I see the scroll bars were reduced, but 

> also, the narrowing on workload / size / etc -- can we carry this on for each CI System (Prow and Jenkins)? 

I was really curious if we could have that left navigation bar for Prow and Jenkins pages?

**Comment by jtaleric** [comment]
also, the Graph.js work should be present, so lets rebase on main

**Comment by chentex** [comment]
> I was really curious if we could have that left navigation bar for Prow and Jenkins pages?

M y idea was to completely remove those pages, since all the jobs will be on the Home page, what are your thoughts?

I asked Thiru to leave the current pages because we don't have all the functionality in the Home page now.

**Comment by athiruma** [comment]
> also, the Graph.js work should be present, so lets rebase on main

Done with rebasing. FIY, I opened this PR against the **test** branch.

**Comment by athiruma** [comment]
Closing the PR, opened the same against main.

**Pull request closed without merging**
