### PR TITLE
New Home page based on the new design mockup

### PR DESCRIPTION
**Pull request by athiruma**
## Type of change

- [x] Refactor
- [x] New feature
- [ ] Bug fix
- [ ] Optimization
- [ ] Documentation Update

## Description

Re-Design the home page.
New Additions:
1. React Redux
2. Home page in a single page.

Backend:
1. Changed the elasticsearch datetime to date type

## Related Tickets & Documents
[https://issues.redhat.com/browse/PERFSCALE-2445](https://issues.redhat.com/browse/PERFSCALE-2445)

- Related Issue #
- Closes #

## Checklist before requesting a review

- [ ] I have performed a self-review of my code.
- [ ] If it is a core feature, I have added thorough tests.

## Testing
- Please describe the System Under Test.
- Please provide detailed steps to perform tests related to this code change.
- How were the fix/results from this change verified? Please provide relevant screenshots or results.
Screenshot 2023-09-26 at 10 06 38 PM

### CODE REVIEW

**Comment by jtaleric** [comment]
Sometimes I see 
image

is that expected?

**Comment by athiruma** [comment]
> Sometimes I see image
> 
> is that expected?

No.
At what time, are you seeing this error?

**Review by chentex — APPROVED** [review]
LGTM

**Review by krishvoor — APPROVED** [review]
/lgtm

**Pull request merged**
