### PR TITLE
Added the grafana/ airflow dashboard card

### PR DESCRIPTION
**Pull request by athiruma**
## Type of change

- [x] Refactor
- [ ] New feature
- [ ] Bug fix
- [ ] Optimization
- [ ] Documentation Update

## Description
Added the grafana/ airflow dashboard card.

## Related Tickets & Documents

- Related Issue #
- Closes #

## Checklist before requesting a review

- [ ] I have performed a self-review of my code.
- [ ] If it is a core feature, I have added thorough tests.

## Testing
- Please describe the System Under Test.
- Please provide detailed steps to perform tests related to this code change.
- How were the fix/results from this change verified? Please provide relevant screenshots or results.
Screenshot 2023-10-02 at 2 21 47 PM

### CODE REVIEW

**Review by jtaleric — COMMENTED** [review]
Can we drop the airflow icon?

**Comment by jtaleric** [comment]
Airflow is no longer in use for PerfScale so i would prefer we wipe it from any of our dashboarding.

**Comment by chentex** [comment]
Probably is a style that is lingering there

**Comment by jtaleric** [comment]
> @jtaleric @chentex If I click on the airflow icon, it navigates me to ProwCi.

lol yeah - can we just drop that icon in this PR?

**Comment by athiruma** [comment]
> > @jtaleric @chentex If I click on the airflow icon, it navigates me to ProwCi.
> 
> lol yeah - can we just drop that icon in this PR?

Done

**Review by chentex — APPROVED** [review]
LGTM

**Pull request merged**
